- name: task level variables
  hosts: local
  connection: local
  vars:
   course: ansible
  tasks:
  - name: printing variables
    ourse: ansible-new
    ansible.builtin.debug:
     msg: "Course name is {{ course }}"