- name: testing loops in playbook
  hosts: local
  connection: local
  tasks:
  - name: loops
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
    loop:
    - mysql
    - nginx